### ISSUE TITLE
TODO: own server setup

### ISSUE THREAD

**Issue by jomo** [crafatar/crafatar#79]
Things that should be done before we switch from heroku to our own server setup

* [x] docker/dokku setup
  * [x] redis
  * [x] Persistent image directory
* [x] Useful nginx logs (i.e. log real IPs, not CloudFlare's)
* [x] persistent log file
  * See `Use forever.js` #74 
* [x] Fix errors with outgoing requests on high load
* [ ] ~~Papertrail alternative (search logs & send alerts)~~ *not important, can do this later*

**Comment by Jake0oo0** [comment]
:+1: for logstash, I currently use it to store huge amounts of log data for another site. I don't know how it will handle this amount of requests though. Does sentry have a free version? Might be a good alternative.

**Comment by jomo** [comment]
https://github.com/getsentry/sentry

**Comment by Jake0oo0** [comment]
https://github.com/getsentry/raven-node

**Comment by jomo** [comment]
A log manager isn't that important, we still have our logs so I think we can skip this and manually filter errors for now.

I think this would be a good approach for switching from heroku to our servers:

* Point cloudflare to new server
* Track CPU / Memory / Disk usage / Logs
* Switch back 10 minutes later
* Analyze logs and tracked data for problems

*Repeat until all problems are fixed (if any)*

* Permanently switch to the new server

**Comment by jomo** [comment]
Might also be useful: https://github.com/lebinh/ngxtop

**Comment by Jake0oo0** [comment]
Broke dokku build with canvas 1.2.1 @jomo

**Comment by rileriscool** [comment]
I'll help host it.

I love Crafatar!

**Comment by Jake0oo0** [comment]
We already have a host sponsoring us, but thanks! :smile:

**Comment by rileriscool** [comment]
Who? :+1:

**Comment by Jake0oo0** [comment]
[Akliz Hosting](http://akliz.net/crafatar)

**Comment by Dark-Arcana** [comment]
:+1:

**Comment by Jake0oo0** [comment]
I got an email from LogEntries about [this](https://logentries.com/doc/docker-logentries-container/) might be of interest

**Comment by jomo** [comment]
So we switched to our [akliz.net](https://akliz.net/crafatar) server, but switched back to heroku again because we noticed a lot of `ETIMEDOUT` and `ESOCKETTIMEDOUT` errors. We need to find out why we are getting those before we switch again.

**Comment by jomo** [comment]
the errors mentioned above are [coming from `request`](https://github.com/request/request/blob/bb578098c09bab2a86c5de6a16adf91734847a1f/request.js#L795-L816). If I read that code correctly:

* `ETIMEDOUT` is thrown if the server fails to answer within the specified timeout
* `ESOCKETTIMEDOUT` is thrown when the server answered within the timeout (which resets the timeout counter) but then fails to send the rest of the data within the specified timeout

When we get a lot of requests, we suddenly get these errors because our `http_timeout` is reached on our requests to Mojang's API.
But contrary to what I did expect, the response time is not increasing until the limit is hit, it just starts hitting the limit from one second to the next. *(they usually take <100ms before)*

It doesn't seem to be related to the amount of currently processed incoming or outgoing number of requests.

@laureled has suggested testing with a fake mojang API server and testing outside of docker. I'll try that as well and post results again.

**Comment by jomo** [comment]
Alright, I created [mojang_fake_api](https://github.com/crafatar/mojang_fake_api) for testing, but other than [funny results](https://i.imgur.com/ZqC8rIW.png) there isn't really anything new.

The fake Mojang requests are now ~22ms and we still suddenly stop getting replies. Apparently the response time is not related to this at all.

In case it helps in understanding, here's a graph:
![graph](https://i.imgur.com/C9fk6K5.png)
*X-Axis = request count x 2*

This was *with docker*, I'll test outside some other day.

**Comment by jomo** [comment]
Just tested this outside docker and it's working without any problems :open_mouth:

**Comment by Jake0oo0** [comment]
When you say outside docker, was that locally or on the Akliz server @jomo? Have we tested just running Crafatar on that server, outside of a docker container? Maybe docker is the problem...?

**Comment by jomo** [comment]
Yes it was on the akliz server and docker does seem to be the problem. I'd like to know if/how we can fix this though.

**Comment by h10998** [comment]
Thanks so much jomo for the mcpeskinstudio thing! I have fixed it, but had to reupload the repository becuase i didnt know how to remove old commits. I'm still learning how to use github :). P.S. Thanks so much for crafatar, i use it alot in my app

**Comment by Jake0oo0** [comment]
Nice job with your app @h10998! :+1:

**Comment by h10998** [comment]
Thanks, we are working on an editor, but are kinda failing xD

**Comment by jomo** [comment]
*(removed some off-topic comments above)*

----

I stalked `lsof -n -u root` while running load tests. The issues started when there were ~4k open files.
So I thought we're getting the errors because we're hitting our `ulimit -Hn` of 4096, but the same happens when running outside docker and that's not causing any issues. In fact, I managed to have *a lot* more open files without any issues.

**Comment by jomo** [comment]
If we can't figure this out, we'll just need to find something for node.js that allows zero-downtime-deployment and management (i.e. rollback).

Some options might be:
* [capostrano-node-deploy](https://github.com/loopj/capistrano-node-deploy)
* [node-deploy](https://github.com/martinrue/node-deploy) (doesn't have rollbacks?)
* [using nginx](http://blog.argteam.com/coding/hardening-node-js-for-production-part-3-zero-downtime-deployments-with-nginx/) (only handles the zero-downtime part using round-robin)

**Comment by jomo** [comment]
FTR: We went without own solution, see [crafatar/substitute](https://github.com/crafatar/substitute).
